packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  '@types/node': ^22.13.14
  hono: ^4.12.27
  '@orpc/server': 2.0.0-beta.18
  '@orpc/openapi': 2.0.0-beta.18
  '@orpc/zod': 2.0.0-beta.18
  '@orpc/client': 2.0.0-beta.18
minimumReleaseAgeExclude:
  - '@orpc/client@2.0.0-beta.18'
  - '@orpc/contract@2.0.0-beta.18'
  - '@orpc/json-schema@2.0.0-beta.18'
  - '@orpc/openapi@2.0.0-beta.18'
  - '@orpc/server@2.0.0-beta.18'
  - '@orpc/shared@2.0.0-beta.18'
  - '@orpc/zod@2.0.0-beta.18'
  - '@expo/cli@57.0.9'
  - '@expo/metro-config@57.0.6'
  - '@expo/prebuild-config@57.0.8'
  - expo-asset@57.0.6
  - expo-constants@57.0.6
  - expo-modules-autolinking@57.0.8
  - expo-modules-core@57.0.6
  - expo@57.0.7
  - '@expo/metro-runtime@57.0.6'
  - '@expo/ui@57.0.7'
  - expo-router@57.0.7
